{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rstmdb.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rstmdb.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
  {{- if .Values.tls.caCert }}
  ca.crt: {{ .Values.tls.caCert | b64enc | quote }}
  {{- end }}
{{- end }}
