{{- if and .Values.auth.required (not .Values.auth.existingSecret) .Values.auth.tokenHashes }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rstmdb.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rstmdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  tokens.secret: |
    {{- range .Values.auth.tokenHashes }}
    {{ . }}
    {{- end }}
{{- end }}
