apiVersion: v1
kind: Service
metadata:
  name: {{ include "rstmdb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rstmdb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: rcp
      port: {{ .Values.service.port }}
      targetPort: rcp
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "rstmdb.selectorLabels" . | nindent 4 }}
---
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rstmdb.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rstmdb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "rstmdb.selectorLabels" . | nindent 4 }}
{{- end }}
