{{- if and .Values.studio.enabled .Values.studio.init.enabled (not .Values.studio.init.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rstmdb.studioFullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rstmdb.studioLabels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.studio.init.username | b64enc | quote }}
  password: {{ .Values.studio.init.password | b64enc | quote }}
{{- end }}
